# Use the official Python image as a base
FROM python:3.12

# Set the working directory
#WORKDIR /IdeaProjects/ui

# Copy all project files to the container
#COPY . /IdeaProjects/ui

# Install any additional dependencies
# RUN pip install --no-cache-dir -r /workspace/requirements.txt